import pandas as pd
import datetime

data = pd.read_csv("data/dataset_extended.csv")

data_recent = data[
    (data["DATE OCC"].str.split().str[0].str[-4:] == "2024")
]

data_recent = data_recent[data_recent["LAT"] != 0]

data_recent["Vict Descent"].replace("X", "", inplace=True)
data_recent["Vict Descent"].fillna("", inplace=True)

ethnicity_dict = {
    "A": "Asian",
    "B": "Black",
    "C": "Chinese",
    "D": "Cambodian",
    "F": "Filipino",
    "G": "Guamanian",
    "H": "Hispanic",
    "I": "Native",
    "J": "Japanese",
    "K": "Korean",
    "L": "Laotian",
    "O": "Other",
    "P": "Pacific",
    "S": "Samoan",
    "U": "Hawaiian",
    "V": "Vietnamese",
    "W": "White",
    "Z": "Indian"
}

data_recent["Vict Descent"] = data_recent["Vict Descent"].map(ethnicity_dict)

crime_categories = {
    'CONTEMPT OF COURT': 'Mixed',
    'THEFT OF IDENTITY': 'Fraud',
    'VIOLATION OF RESTRAINING ORDER': 'Mixed',
    'DOCUMENT FORGERY / STOLEN FELONY': 'Fraud',
    'SHOPLIFTING - PETTY THEFT ($950 & UNDER)': 'Property',
    'BURGLARY FROM VEHICLE': 'Property',
    'LETTERS, LEWD  -  TELEPHONE CALLS, LEWD': 'Mixed',
    'THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LIVESTK,PROD': 'Property',
    'BATTERY WITH SEXUAL CONTACT': 'Violent',
    'INTIMATE PARTNER - SIMPLE ASSAULT': 'Violent',
    'CRM AGNST CHLD (13 OR UNDER) (14-15 & SUSP 10 YRS OLDER)': 'Sexual',
    'BATTERY ON A FIREFIGHTER': 'Violent',
    'CHILD STEALING': 'Violent',
    'SEXUAL PENETRATION W/FOREIGN OBJECT': 'Sexual',
    'BUNCO, GRAND THEFT': 'Fraud',
    'THEFT FROM MOTOR VEHICLE - GRAND ($950.01 AND OVER)': 'Property',
    'CHILD ANNOYING (17YRS & UNDER)': 'Sexual',
    'CRIMINAL HOMICIDE': 'Violent',
    'THEFT PLAIN - PETTY ($950 & UNDER)': 'Property',
    'ORAL COPULATION': 'Sexual',
    'VEHICLE - STOLEN': 'Property',
    'SEX,UNLAWFUL(INC MUTUAL CONSENT, PENETRATION W/ FRGN OBJ': 'Sexual',
    'UNAUTHORIZED COMPUTER ACCESS': 'Fraud',
    'EMBEZZLEMENT, GRAND THEFT ($950.01 & OVER)': 'Fraud',
    'STALKING': 'Violent',
    'INTIMATE PARTNER - AGGRAVATED ASSAULT': 'Violent',
    'RAPE, FORCIBLE': 'Sexual',
    'VANDALISM - FELONY ($400 & OVER, ALL CHURCH VANDALISMS)': 'Property',
    'ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT': 'Violent',
    'BURGLARY': 'Property',
    'BATTERY - SIMPLE ASSAULT': 'Violent',
    'THEFT FROM MOTOR VEHICLE - PETTY ($950 & UNDER)': 'Property',
    'HUMAN TRAFFICKING - COMMERCIAL SEX ACTS': 'Sexual',
    'SEX OFFENDER REGISTRANT OUT OF COMPLIANCE': 'Sexual',
    'OTHER Mixed CRIME': 'Mixed',
    'BUNCO, ATTEMPT': 'Fraud',
    'ROBBERY': 'Violent',
    'CREDIT CARDS, FRAUD USE ($950.01 & OVER)': 'Fraud',
    'TRESPASSING': 'Mixed',
    'DOCUMENT WORTHLESS ($200.01 & OVER)': 'Fraud',
    'LEWD/LASCIVIOUS ACTS WITH CHILD': 'Sexual',
    'BRANDISH WEAPON': 'Violent',
    'HUMAN TRAFFICKING - INVOLUNTARY SERVITUDE': 'Sexual',
    'VEHICLE - ATTEMPT STOLEN': 'Property',
    'CHILD ABUSE (PHYSICAL) - SIMPLE ASSAULT': 'Violent',
    'CHILD PORNOGRAPHY': 'Sexual',
    'SODOMY/SEXUAL CONTACT B/W PENIS OF ONE PERS TO ANUS OTH': 'Sexual',
    'DISCHARGE FIREARMS/SHOTS FIRED': 'Violent',
    'CRUELTY TO ANIMALS': 'Mixed',
    'BIKE - STOLEN': 'Property',
    'BUNCO, PETTY THEFT': 'Fraud',
    'VANDALISM - MISDEAMEANOR ($399 OR UNDER)': 'Property',
    'CRIMINAL THREATS - NO WEAPON DISPLAYED': 'Violent',
    'EXTORTION': 'Fraud',
    'VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, BIKES, ETC)': 'Property',
    'VIOLATION OF COURT ORDER': 'Mixed',
    'PEEPING TOM': 'Sexual',
    'PICKPOCKET': 'Property',
    'ARSON': 'Property',
    'FAILURE TO YIELD': 'Mixed',
    'EMBEZZLEMENT, PETTY THEFT ($950 & UNDER)': 'Fraud',
    'SHOPLIFTING-GRAND THEFT ($950.01 & OVER)': 'Property',
    'BIGAMY': 'Mixed',
    'WEAPONS POSSESSION/BOMBING': 'Violent',
    'CHILD ABUSE (PHYSICAL) - AGGRAVATED ASSAULT': 'Violent',
    'DISTURBING THE PEACE': 'Mixed',
    'THEFT, PERSON': 'Property',
    'INDECENT EXPOSURE': 'Sexual',
    'PROWLER': 'Mixed',
    'LEWD CONDUCT': 'Sexual',
    'CHILD NEGLECT (SEE 300 W.I.C.)': 'Mixed',
    'MANSLAUGHTER, NEGLIGENT': 'Violent',
    'BURGLARY, ATTEMPTED': 'Property',
    'BATTERY POLICE (SIMPLE)': 'Violent',
    'BOAT - STOLEN': 'Property',
    'KIDNAPPING': 'Violent',
    'OTHER ASSAULT': 'Violent',
    'FALSE POLICE REPORT': 'Mixed',
    'BOMB SCARE': 'Mixed',
    'SHOTS FIRED AT MOVING VEHICLE, TRAIN OR AIRCRAFT': 'Violent',
    'FALSE IMPRISONMENT': 'Violent',
    'ATTEMPTED ROBBERY': 'Violent',
    'THROWING OBJECT AT MOVING VEHICLE': 'Mixed',
    'DISHONEST EMPLOYEE - GRAND THEFT': 'Fraud',
    'RESISTING ARREST': 'Mixed',
    'DISHONEST EMPLOYEE ATTEMPTED THEFT': 'Fraud',
    'CREDIT CARDS, FRAUD USE ($950 & UNDER': 'Fraud',
    'THEFT PLAIN - ATTEMPT': 'Property',
    'THREATENING PHONE CALLS/LETTERS': 'Mixed',
    'BURGLARY FROM VEHICLE, ATTEMPTED': 'Property',
    'CONTRIBUTING': 'Mixed',
    'PIMPING': 'Sexual',
    'DEFRAUDING INNKEEPER/THEFT OF SERVICES, $950 & UNDER': 'Fraud',
    'DOCUMENT WORTHLESS ($200 & UNDER)': 'Fraud',
    'RAPE, ATTEMPTED': 'Sexual',
    'VIOLATION OF TEMPORARY RESTRAINING ORDER': 'Mixed',
    'SHOTS FIRED AT INHABITED DWELLING': 'Violent',
    'PANDERING': 'Sexual',
    'THEFT, COIN MACHINE - PETTY ($950 & UNDER)': 'Property',
    'RECKLESS DRIVING': 'Mixed',
    'THEFT FROM MOTOR VEHICLE - ATTEMPT': 'Property',
    'DEFRAUDING INNKEEPER/THEFT OF SERVICES, OVER $950.01': 'Fraud',
    'ASSAULT WITH DEADLY WEAPON ON POLICE OFFICER': 'Violent',
    'DRIVING WITHOUT OWNER CONSENT (DWOC)': 'Property',
    'KIDNAPPING - GRAND ATTEMPT': 'Violent',
    'GRAND THEFT / INSURANCE FRAUD': 'Fraud',
    'THEFT FROM PERSON - ATTEMPT': 'Property',
    'INCITING A RIOT': 'Mixed',
    'SHOPLIFTING - ATTEMPT': 'Property',
    'COUNTERFEIT': 'Fraud',
    'CONSPIRACY': 'Mixed',
    'ILLEGAL DUMPING': 'Mixed',
    'DISHONEST EMPLOYEE - PETTY THEFT': 'Fraud',
    'TILL TAP - GRAND THEFT ($950.01 & OVER)': 'Property',
    'FAILURE TO DISPERSE': 'Mixed',
    'REPLICA FIREARMS(SALE,DISPLAY,MANUFACTURE OR DISTRIBUTE)': 'Mixed',
    'TELEPHONE PROPERTY - DAMAGE': 'Property',
    'PURSE SNATCHING - ATTEMPT': 'Property',
    'PURSE SNATCHING': 'Property',
    'LYNCHING': 'Violent',
    'CHILD ABANDONMENT': 'Mixed',
    'THEFT, COIN MACHINE - ATTEMPT': 'Property',
    'INCEST (SEXUAL ACTS BETWEEN BLOOD RELATIVES)': 'Sexual',
    'TRAIN WRECKING': 'Mixed',
    'TILL TAP - PETTY ($950 & UNDER)': 'Property',
    'DISRUPT SCHOOL': 'Mixed',
    'DRUNK ROLL': 'Mixed',
    'PICKPOCKET, ATTEMPT': 'Property'
}

data_recent["Crm Cd Desc"] = data_recent["Crm Cd Desc"].map(crime_categories)
data_recent["Crm Cd Desc"].fillna("Mixed", inplace=True)
data_recent["month"] = data_recent["DATE OCC"].str.split("/").str[0].astype(int)

data_recent["Date.Format"] = data_recent['DATE OCC'].apply(
    lambda x: datetime.datetime.strptime(x.split()[0], "%m/%d/%Y").strftime("%d %B, %Y")
).fillna("Unknown")
weapon_mapping = {
    'Strong-arm (hands, fist, feet or bodily force)': 'Physical force',
    'Unknown weapon/other weapon': 'Other/Unknown',
    'Mace/pepper spray': 'Chemical weapon',
    'Scissors': 'Sharp instrument',
    'Knife with blade 6inches or less': 'Knife',
    'Verbal threat': 'Verbal threat',
    'Other knife': 'Knife',
    'Vehicle': 'Vehicle',
    'Hand gun': 'Firearm',
    'Stick': 'Blunt instrument',
    'Razor blade': 'Sharp instrument',
    'Air pistol/revolver/rifle/bb gun': 'Air gun',
    'Hammer': 'Blunt instrument',
    'Fire': 'Fire',
    'Heckler & koch 93 semiautomatic assault rifle': 'Assault rifle',
    'Fixed object': 'Blunt instrument',
    'Unknown firearm': 'Firearm',
    'Other cutting instrument': 'Sharp instrument',
    'Rifle': 'Firearm',
    'Semi-automatic pistol': 'Firearm',
    'Kitchen knife': 'Knife',
    'Folding knife': 'Knife',
    'Rock/thrown object': 'Blunt instrument',
    'Bottle': 'Blunt instrument',
    'Pipe/metal pipe': 'Blunt instrument',
    'Physical presence': 'Physical force',
    'Club/bat': 'Blunt instrument',
    'Revolver': 'Firearm',
    'Glass': 'Sharp instrument',
    'Unknown type cutting instrument': 'Sharp instrument',
    'Screwdriver': 'Sharp instrument',
    'Knife with blade over 6 inches in length': 'Knife',
    'Concrete block/brick': 'Blunt instrument',
    'Razor': 'Sharp instrument',
    'Machete': 'Sharp instrument',
    'Ice pick': 'Sharp instrument',
    'Simulated gun': 'Simulated gun',
    'Board': 'Blunt instrument',
    'Tire iron': 'Blunt instrument',
    'Brass knuckles': 'Blunt instrument',
    'Bomb threat': 'Explosive threat',
    'Switch blade': 'Knife',
    'Straight razor': 'Sharp instrument',
    'Belt flailing instrument/chain': 'Blunt instrument',
    'Unk type semiautomatic assault rifle': 'Assault rifle',
    'Caustic chemical/poison': 'Chemical weapon',
    'Blunt instrument': 'Blunt instrument',
    'Axe': 'Sharp instrument',
    'Other firearm': 'Firearm',
    'Scalding liquid': 'Chemical weapon',
    'Dirk/dagger': 'Sharp instrument',
    'Sword': 'Sharp instrument',
    'Toy gun': 'Simulated gun',
    'Dog/animal (sic animal on)': 'Animal',
    'Shotgun': 'Firearm',
    'Stun gun': 'Electric weapon',
    'Relic firearm': 'Firearm',
    'Demand note': 'Verbal threat',
    'Rope/ligature': 'Ligature',
    'Cleaver': 'Sharp instrument',
    'Assault weapon/uzi/ak47/etc': 'Assault rifle',
    'Semi-automatic rifle': 'Assault rifle',
    'Automatic weapon/sub-machine gun': 'Automatic weapon',
    'Exploxive device': 'Explosive device',
    'Syringe': 'Sharp instrument',
    'Martial arts weapons': 'Martial arts weapon',
    'Starter pistol/revolver': 'Simulated gun',
    'Bow and arrow': 'Projectile weapon',
    'Liquor/drugs': 'Chemical weapon',
    'M-14 semiautomatic assault rifle': 'Assault rifle',
    'Bowie knife': 'Knife',
}

data_recent["Weapon Desc"] = (data_recent["Weapon Desc"]
    .str.capitalize()
    .map(weapon_mapping)
    .fillna("Other/Unknown")
)

location_mapping = {
    'MISSIONS/SHELTERS': 'Shelter/Housing',
    'SIDEWALK': 'Outdoor/Public Space',
    'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)': 'Residential',
    'RESTAURANT/FAST FOOD': 'Food Establishment',
    'STREET': 'Outdoor/Public Space',
    'SINGLE FAMILY DWELLING': 'Residential',
    'CONDOMINIUM/TOWNHOUSE': 'Residential',
    'OTHER BUSINESS': 'Business/Commercial',
    'VEHICLE, PASSENGER/TRUCK': 'Vehicle',
    'MTA - RED LINE - WESTLAKE/MACARTHUR PARK': 'Public Transportation',
    'DEPARTMENT STORE': 'Retail',
    'PORCH, RESIDENTIAL': 'Residential',
    'HEALTH SPA/GYM': 'Recreation/Leisure',
    'PARKING LOT': 'Parking',
    'DRIVEWAY': 'Parking',
    'GARAGE/CARPORT': 'Parking',
    'AUTO DEALERSHIP (CHEVY, FORD, BMW, MERCEDES, ETC.)': 'Business/Commercial',
    'AUTO SUPPLY STORE*': 'Retail',
    'LA UNION STATION (NOT LINE SPECIFIC)': 'Public Transportation',
    'MTA BUS': 'Public Transportation',
    'OTHER PREMISE': 'Other/Unknown',
    'GAS STATION': 'Business/Commercial',
    'MTA PROPERTY OR PARKING LOT': 'Public Transportation',
    'HIGH SCHOOL': 'Education',
    'ALLEY': 'Outdoor/Public Space',
    'DRIVE THRU*': 'Business/Commercial',
    'GARMENT MANUFACTURER': 'Business/Commercial',
    'OTHER RESIDENCE': 'Residential',
    'YARD (RESIDENTIAL/BUSINESS)': 'Outdoor/Public Space',
    'MOTEL': 'Accommodation',
    'CLOTHING STORE': 'Retail',
    'COLLEGE/JUNIOR COLLEGE/UNIVERSITY': 'Education',
    'TRAIN DEPOT/TERMINAL, OTHER THAN MTA': 'Public Transportation',
    'HARDWARE/BUILDING SUPPLY': 'Retail',
    'NIGHT CLUB (OPEN EVENINGS ONLY)': 'Recreation/Leisure',
    'JUNIOR HIGH SCHOOL': 'Education',
    'PARK/PLAYGROUND': 'Outdoor/Public Space',
    'MTA - RED LINE - UNION STATION': 'Public Transportation',
    'FIRE STATION': 'Government Facility',
    'CONSTRUCTION SITE': 'Business/Commercial',
    'DRUG STORE': 'Retail',
    'DAY CARE/ADULTS*': 'Care Facility',
    'HOTEL': 'Accommodation',
    'HIGH-RISE BUILDING': 'Residential',
    "COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET'S, ETC.)": 'Food Establishment',
    'OTHER/OUTSIDE': 'Outdoor/Public Space',
    'MAIL BOX': 'Business/Commercial',
    'LIQUOR STORE': 'Retail',
    'MTA - RED LINE - PERSHING SQUARE': 'Public Transportation',
    'WAREHOUSE': 'Business/Commercial',
    'PUBLIC STORAGE': 'Business/Commercial',
    'OTHER STORE': 'Retail',
    'PARKING UNDERGROUND/BUILDING': 'Parking',
    'CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)': 'Place of Worship',
    'AUTOMATED TELLER MACHINE (ATM)': 'Business/Commercial',
    'MTA - BLUE LINE - GRAND/LATTC': 'Public Transportation',
    'EQUIPMENT RENTAL': 'Business/Commercial',
    'THEATRE/MOVIE': 'Recreation/Leisure',
    'STUDIO (FILM/PHOTOGRAPHIC/MUSIC)': 'Business/Commercial',
    'MTA - RED LINE - NORTH HOLLYWOOD': 'Public Transportation',
    'DETENTION/JAIL FACILITY': 'Government Facility',
    'HOSPITAL': 'Health Facility',
    'ELEMENTARY SCHOOL': 'Education',
    'BANK': 'Business/Commercial',
    'DAY CARE/CHILDREN*': 'Care Facility',
    'CAR WASH': 'Business/Commercial',
    'BAR/SPORTS BAR (OPEN DAY & NIGHT)': 'Food Establishment',
    'MARKET': 'Retail',
    'VETERINARIAN/ANIMAL HOSPITAL': 'Health Facility',
    'MINI-MART': 'Retail',
    'THE BEVERLY CONNECTION': 'Shopping Mall',
    'ABANDONED BUILDING ABANDONED HOUSE': 'Other/Unknown',
    'PRIVATE SCHOOL/PRESCHOOL': 'Education',
    'BAR/COCKTAIL/NIGHTCLUB': 'Recreation/Leisure',
    'MTA - RED LINE - VERMONT/SUNSET': 'Public Transportation',
    'DISCOUNT STORE (99 CENT,DOLLAR,ETC.': 'Retail',
    'THE BEVERLY CENTER': 'Shopping Mall',
    'AUTO REPAIR SHOP': 'Business/Commercial',
    'JEWELRY STORE': 'Retail',
    'TRANSPORTATION FACILITY (AIRPORT)': 'Public Transportation',
    'PATIO*': 'Outdoor/Public Space',
    'NURSING/CONVALESCENT/RETIREMENT HOME': 'Care Facility',
    'HOSPICE': 'Care Facility',
    'BOOK STORE': 'Retail',
    'OFFICE BUILDING/OFFICE': 'Business/Commercial',
    'VACANT LOT': 'Other/Unknown',
    'MTA - ORANGE LINE - CANOGA': 'Public Transportation',
    'MTA - EXPO LINE - EXPO/CRENSHAW': 'Public Transportation',
    'SHOPPING MALL (COMMON AREA)': 'Shopping Mall',
    "DIY CENTER (LOWE'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)": 'Retail',
    'ENTERTAINMENT/COMEDY CLUB (OTHER)': 'Recreation/Leisure',
    'BUS-CHARTER/PRIVATE': 'Public Transportation',
    'MANUFACTURING COMPANY': 'Business/Commercial',
    'POLICE FACILITY': 'Government Facility',
    'GROUP HOME': 'Care Facility',
    'MEDICAL/DENTAL OFFICES': 'Health Facility',
    'LAUNDROMAT': 'Business/Commercial',
    'RIVER BED*': 'Outdoor/Public Space',
    'BEAUTY SUPPLY STORE': 'Retail',
    'BUS STOP/LAYOVER (ALSO QUERY 124)': 'Public Transportation',
    'MEMBERSHIP STORE (COSTCO,SAMS CLUB)*': 'Retail',
    'PET STORE': 'Retail',
    'TRANSITIONAL HOUSING/HALFWAY HOUSE': 'Care Facility',
    'GUN/SPORTING GOODS': 'Retail',
    'CHECK CASHING*': 'Business/Commercial',
    'MTA - PURPLE LINE - WILSHIRE/WESTERN': 'Public Transportation',
    'MTA - GREEN LINE - AVALON': 'Public Transportation',
    'MTA - RED LINE - 7TH AND METRO CENTER': 'Public Transportation',
    'NURSERY/FLOWER SHOP': 'Retail',
    'MTA - RED LINE - HOLLYWOOD/HIGHLAND': 'Public Transportation',
    'BALCONY*': 'Residential',
    'MTA - RED LINE - UNIVERSAL CITY/STUDIO CITY': 'Public Transportation',
    'THE GROVE': 'Shopping Mall',
    'METROLINK TRAIN': 'Public Transportation',
    'TAXI': 'Public Transportation',
    "MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV'S/MOTORHOME": 'Residential',
    'BUS STOP': 'Public Transportation',
    'CELL PHONE STORE': 'Retail',
    'TUNNEL': 'Outdoor/Public Space',
    'LIBRARY': 'Education',
    'MTA - GOLD LINE - SOUTHWEST MUSEUM': 'Public Transportation',
    'BEACH': 'Outdoor/Public Space',
    'MTA - EXPO LINE - LA CIENEGA/JEFFERSON': 'Public Transportation',
    'GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)': 'Government Facility',
    'CLEANER/LAUNDROMAT': 'Business/Commercial',
    'BUS, SCHOOL, CHURCH': 'Public Transportation',
    'AUTO SALES LOT': 'Business/Commercial',
    'MTA - BLUE LINE - 7TH AND METRO CENTER': 'Public Transportation',
    'FRAT HOUSE/SORORITY/DORMITORY': 'Residential',
    'AMUSEMENT PARK*': 'Recreation/Leisure',
    'MTA - ORANGE LINE - WOODMAN': 'Public Transportation',
    'TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*': 'Education',
    'MTA - RED LINE - HOLLYWOOD/WESTERN': 'Public Transportation',
    'MTA - RED LINE - WILSHIRE/VERMONT': 'Public Transportation',
    'MTA - GOLD LINE - LITTLE TOKYO/ARTS DISTRICT': 'Public Transportation',
    'MTA - GOLD LINE - MARIACHI PLAZA': 'Public Transportation',
    'MTA - RED LINE - VERMONT/BEVERLY': 'Public Transportation',
    'OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*': 'Retail',
    'FACTORY': 'Business/Commercial',
    'MTA - PURPLE LINE - WILSHIRE/VERMONT': 'Public Transportation',
    'DAM/RESERVOIR': 'Outdoor/Public Space',
    '7TH AND METRO CENTER (NOT LINE SPECIFIC)': 'Public Transportation',
    'TRANSIENT ENCAMPMENT': 'Outdoor/Public Space',
    'MTA - RED LINE - HOLLYWOOD/VINE': 'Public Transportation',
    'TOBACCO SHOP': 'Retail',
    'MTA - GOLD LINE - INDIANA': 'Public Transportation',
    'WEBSITE': 'Other/Unknown',
    'STORAGE SHED': 'Business/Commercial',
    'PHARMACY INSIDE STORE OR SUPERMARKET*': 'Retail',
    'SYNAGOGUE/TEMPLE': 'Place of Worship',
    'POST OFFICE': 'Government Facility',
    'VISION CARE FACILITY*': 'Health Facility',
    'MTA - GOLD LINE - LINCOLN/CYPRESS': 'Public Transportation',
    'SPECIALTY SCHOOL/OTHER': 'Education',
    'BEAUTY/BARBER SHOP': 'Retail',
    'PAWN SHOP': 'Retail',
    'STAPLES CENTER *': 'Recreation/Leisure',
    'MTA - PURPLE LINE - WILSHIRE/NORMANDIE': 'Public Transportation',
    'DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*': 'Business/Commercial',
    'MTA - ORANGE LINE - RESEDA': 'Public Transportation',
    'CYBERSPACE': 'Other/Unknown',
    'TELECOMMUNICATION FACILITY/LOCATION': 'Business/Commercial',
    'MTA - EXPO LINE - PICO': 'Public Transportation',
    'GOLF COURSE*': 'Recreation/Leisure',
    'CONVENTION CENTER': 'Recreation/Leisure',
    'NAIL SALON': 'Retail',
    float('nan'): 'Other/Unknown',
    'MTA - EXPO LINE - EXPO/BUNDY': 'Public Transportation',
    'FURNITURE STORE': 'Retail',
    'BASKETBALL COURTS': 'Recreation/Leisure',
    'DODGER STADIUM': 'Recreation/Leisure',
    'MTA - GOLD LINE - HERITAGE SQ': 'Public Transportation',
    'MTA - BLUE LINE - SAN PEDRO': 'Public Transportation',
    'SWAP MEET': 'Retail',
    'MTA - RED LINE - CIVIC CENTER/GRAND PARK': 'Public Transportation',
    'MTA - GOLD LINE - SOTO': 'Public Transportation',
    'MTA - GOLD LINE - CHINATOWN': 'Public Transportation',
    'FREEWAY': 'Outdoor/Public Space',
    'MASSAGE PARLOR': 'Recreation/Leisure',
    'SHORT-TERM VACATION RENTAL': 'Accommodation',
    'MTA - GREEN LINE - AVIATION/LAX': 'Public Transportation',
    'MTA - EXPO LINE - LATTC/ORTHO INSTITUTE': 'Public Transportation',
    'PUBLIC RESTROOM(INDOORS-INSIDE)': 'Public Facility',
    'BOWLING ALLEY*': 'Recreation/Leisure',
    'MTA - BLUE LINE - 103RD/WATTS TOWERS': 'Public Transportation',
    'ESCALATOR*': 'Public Facility',
    'MUSEUM': 'Recreation/Leisure',
    'MTA - RED LINE - VERMONT/SANTA MONICA': 'Public Transportation',
    'SPORTS ARENA': 'Recreation/Leisure',
    'TRAIN TRACKS': 'Public Transportation',
    'ELECTRONICS STORE (IE:RADIO SHACK, ETC.)': 'Retail',
    'MTA - GOLD LINE - PICO/ALISO': 'Public Transportation',
    'MUNICIPAL BUS LINE INCLUDES LADOT/DASH': 'Public Transportation',
    'TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)': 'Public Transportation',
    'SPORTS VENUE, OTHER': 'Recreation/Leisure',
    'TOW YARD*': 'Business/Commercial',
    'MTA - ORANGE LINE - VALLEY COLLEGE': 'Public Transportation',
    "SINGLE RESIDENCE OCCUPANCY (SRO'S) LOCATIONS": 'Residential',
    'MTA - BLUE LINE - WASHINGTON': 'Public Transportation',
    'MTA - EXPO LINE - EXPO/WESTERN': 'Public Transportation',
    'COMPUTER SERVICES/REPAIRS/SALES': 'Business/Commercial',
    'APARTMENT/CONDO COMMON LAUNDRY ROOM': 'Residential',
    'MTA - GOLD LINE - UNION STATION': 'Public Transportation',
    'SKATEBOARD FACILITY/SKATEBOARD PARK*': 'Recreation/Leisure',
    'MTA - EXPO LINE - EXPO/VERMONT': 'Public Transportation',
    'AIRCRAFT': 'Public Transportation',
    'VALET': 'Business/Commercial',
    'MTA - GOLD LINE - HIGHLAND PARK': 'Public Transportation',
    'RECYCLING CENTER': 'Business/Commercial',
    "VEHICLE STORAGE LOT (CARS, TRUCKS, RV'S, BOATS, TRAILERS, ETC.)": 'Business/Commercial',
    'CATERING/ICE CREAM TRUCK': 'Business/Commercial',
    'MTA - EXPO LINE - PALMS': 'Public Transportation',
    'MTA - BLUE LINE - PICO': 'Public Transportation',
    'COLISEUM': 'Recreation/Leisure',
    'PROJECT/TENEMENT/PUBLIC HOUSING': 'Residential',
    'AMTRAK TRAIN': 'Public Transportation',
    'MTA - EXPO LINE - EXPO/SEPULVEDA': 'Public Transportation',
    'MTA - ORANGE LINE - CHATSWORTH': 'Public Transportation',
    'PUBLIC RESTROOM/OUTSIDE*': 'Public Facility',
    'FOSTER HOME BOYS OR GIRLS*': 'Care Facility',
    'MTA - EXPO LINE - EXPO PARK/USC': 'Public Transportation',
    'TERMINAL, OTHER THAN MTA': 'Public Transportation',
    'CEMETARY*': 'Outdoor/Public Space',
    'MTA - ORANGE LINE - SEPULVEDA': 'Public Transportation',
    'MTA - GREEN LINE - HARBOR FWY': 'Public Transportation',
    'WATER FACILITY': 'Business/Commercial',
    'MTA - EXPO LINE - EXPO/LA BREA': 'Public Transportation',
    'ELEVATOR': 'Public Facility',
    'STAIRWELL*': 'Public Facility',
    'MTA - EXPO LINE - FARMDALE': 'Public Transportation',
    'BUS DEPOT/TERMINAL, OTHER THAN MTA': 'Public Transportation',
    'TATTOO PARLOR*': 'Retail',
    'MOSQUE*': 'Place of Worship',
    'SLIPS/DOCK/MARINA/BOAT': 'Public Transportation',
    'MEDICAL MARIJUANA FACILITIES/BUSINESSES': 'Retail',
    'OTHER PLACE OF WORSHIP': 'Place of Worship',
    'METHADONE CLINIC': 'Health Facility',
    'OTHER RR TRAIN (UNION PAC, SANTE FE ETC': 'Public Transportation',
    'ENERGY PLANT/FACILITY': 'Business/Commercial',
    'MTA - EXPO LINE - JEFFERSON/USC': 'Public Transportation',
    'VIDEO RENTAL STORE': 'Retail',
    'MTA - SILVER LINE - HARBOR GATEWAY TRANSIT CTR': 'Public Transportation',
    'POOL-PUBLIC/OUTDOOR OR INDOOR*': 'Recreation/Leisure',
    'OIL REFINERY': 'Business/Commercial',
    'ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*': 'Recreation/Leisure',
    'TOOL SHED*': 'Business/Commercial',
    "SEX ORIENTED/BOOK STORE/STRIP CLUB/GENTLEMAN'S CLUB": 'Recreation/Leisure',
    'MTA - ORANGE LINE - NORTH HOLLYWOOD': 'Public Transportation',
    'CULTURAL SIGNIFICANCE/MONUMENT': 'Recreation/Leisure',
    'MTA - EXPO LINE - WESTWOOD/RANCHO PARK': 'Public Transportation',
    'UNDERPASS/BRIDGE*': 'Outdoor/Public Space',
    'MORTUARY': 'Other/Unknown',
    'GREYHOUND OR INTERSTATE BUS': 'Public Transportation',
    'SAVINGS & LOAN': 'Business/Commercial',
    'PEDESTRIAN OVERCROSSING': 'Outdoor/Public Space',
    'ABORTION CLINIC/ABORTION FACILITY*': 'Health Facility',
    'RECORD-CD MUSIC/COMPUTER GAME STORE': 'Retail',
    'MTA - SILVER LINE - SLAUSON': 'Public Transportation',
    'DRIVE THRU BANKING (WINDOW)*': 'Business/Commercial',
    'TRASH CAN/TRASH DUMPSTER': 'Outdoor/Public Space',
    'MTA - BLUE LINE - VERNON': 'Public Transportation',
    'MTA - SILVER LINE - MANCHESTER': 'Public Transportation',
    'CREDIT UNION': 'Business/Commercial',
    'MTA - ORANGE LINE - LAUREL CANYON': 'Public Transportation',
    'FINANCE COMPANY': 'Business/Commercial',
    'MTA - EXPO LINE - 7TH AND METRO CENTER': 'Public Transportation',
    'PAY PHONE': 'Other/Unknown'
}

data_recent["Premis Desc"] = (data_recent["Premis Desc"]
    .map(location_mapping)
    .fillna("Other/Unknown")
)

sex_mapping = {
    "F": "Female",
    "M": "Male",
    "X": "Unknown",
    "H": "Homosexual"
}

data_recent["Vict Sex"] = data_recent["Vict Sex"].map(sex_mapping).fillna("Unknown")

data_recent["AREA NAME"].replace("N Hollywood", "North Hollywood", inplace=True)

data_recent.to_csv("data/dataset_recent.csv")